username = foltik
password = UFqE!a&oUUC#y7kS
spotify-id = 1551f47f14ad40ed9d3c10f28c081b5f
spotify-secret = ccb69b8a268a4ec8bbd698909cf5c56a
spotify-refresh = AQAF8UnlchVuDApF51ILGO5AeXAoAs7faIcYHtFpq6jhKzgsfv2XNNimbr6j2FhJz_yzke53ocfJzN-p5h0sskrMd5iLITYAbPAvp1vQezG2Jgcq_hoZEqHokGDo-DZGl-k
path = ~/music
pref-format = flac,mp3
