#!/bin/sh

"$DOTS/files/xinput.sh"

# Give the on-demand xdg-desktop-portal backend a display, else file pickers fail.
export XDG_CURRENT_DESKTOP=GTK
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP

exec dwm
