#!/bin/bash
# Helper for .ssh/config Match rules that succeeds only for an interactive `ssh <host>`
set -euo pipefail
exec 2>/dev/null

[ "$(cat /proc/$PPID/comm)" = ssh ]             # Parent is a real ssh client
readlink /proc/$PPID/fd/0 | grep -q ^/dev/pts/  # With a terminal on stdin

# Shift off all ssh command line options
mapfile -d '' -t argv < /proc/$PPID/cmdline
set -- "${argv[@]:1}"
while [[ ${1-} == -* ]]; do
  case $1 in
    --) shift; break ;;
    -[BbcDEeFIiJLlmOoPpQRSWw]) shift 2 ;;  # Options taking a separate argument
    *) shift ;;
  esac
done

# Interactive iff destination is the only arg left
[ $# -eq 1 ]
